[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
libc = "0.2.80"
cpuid = "0.1.1"
psutil = "3.2.0"
dotenv = "0.15.0"
utmp-rs = "0.1.1"
env_logger = "0.8.1"
mac_address = "1.1.1"
serde = { version = "1.0", features = ["derive"] }
os_info = { version = "3.0", default-features = false }
reqwest = { version = "0.10", features = ["blocking", "json"] }
