[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19.0"
dirs = "3.0.1"
log = "0.4.11"
libc = "0.2.80"
text_io = "0.1.8"
env_logger = "0.8.1"
serde_json = "1.0.59"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }

[target.'cfg(target_os = "linux")'.dependencies]
unescape = "0.1.0"

[target.'cfg(target_os = "macos")'.dependencies]
io-kit-sys = "0.1.0"
core-foundation-sys = "0.8.2"
mach = "0.3"

[dev-dependencies]
criterion = "0.3"

[lib]
name = "metrics"
path = "src/metrics/lib.rs"
bench = false

[[bin]]
name = "speculare-client"
path = "src/main.rs"
bench = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[[bench]]
name = "global_bench"
harness = false

[[bench]]
name = "cpu_bench"
harness = false

[[bench]]
name = "disks_bench"
harness = false

[[bench]]
name = "memory_bench"
harness = false

[[bench]]
name = "miscs_bench"
harness = false

[[bench]]
name = "network_bench"
harness = false

[[bench]]
name = "users_bench"
harness = false