[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
env_logger = "0.8.2"
log = "0.4.11"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
sys_metrics = { git = "https://github.com/Martichou/sys_metrics" }
text_io = "0.1.8"

[[bin]]
name = "speculare-client"
path = "src/main.rs"
bench = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1