[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sys-info = "0.7"

dirs = "3.0.1"
log = "0.4.11"
libc = "0.2.80"
cpuid = "0.1.1"
text_io = "0.1.8"
env_logger = "0.8.1"
mac_address = "1.1.1"
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
os_info = { version = "3.0", default-features = false }
psutil = { git = "https://github.com/Martichou/rust-psutil" }
reqwest = { version = "0.10", features = ["blocking", "json"] }

[dev-dependencies]
criterion = "0.3"

[lib]
name = "metrics_rs"
path = "src/metrics/lib.rs"
bench = false

[[bin]]
name = "speculare-client"
path = "src/main.rs"
bench = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[[bench]]
name = "cpu_bench"
harness = false

[[bench]]
name = "disks_bench"
harness = false

[[bench]]
name = "memory_bench"
harness = false

[[bench]]
name = "miscs_bench"
harness = false

[[bench]]
name = "network_bench"
harness = false

[[bench]]
name = "sensors_bench"
harness = false

[[bench]]
name = "users_bench"
harness = false