[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.7.0"
sysinfo = "0.15.3"
machine-uid = "0.2.0"
os-version = "0.1.1"
