[package]
name = "speculare-client"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
chrono = { version = "0.4", features = ["serde"] }
dirs-next = "2.0.0"
env_logger = "0.8.2"
hyper = "0.13.9"
hyper-tls = "0.4.3"
log = "0.4.11"
num-integer = "0.1"
serde_json = "1.0.60"
serde = { version = "1.0", features = ["derive"] }
sys_metrics = { git = "https://github.com/Martichou/sys_metrics" }
text_io = "0.1.8"
tokio = { version = "0.2", features = ["full"] }

[[bin]]
name = "speculare-client"
path = "src/main.rs"
bench = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1