name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: macOS-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Build
      run: cargo check

  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Run tests
      run: cargo test
